/****************************************************************************************
 * Vresion               Date              Author                 Description
 * ============================================================================================
 * v1.0                  2025-06-02       Bipul Singhdeo           Add method implementation
 */
public with sharing class Calculator {
    public Calculator() {

     }
     public integer add(Integer a, Integer b) {
         return a + b;
     }
     public Integer sub(Integer a, Integer b) {
         return a - b;
     }
}
